# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true


[[main]]
identifier = "original"
name = "オリジナル曲"
url = "/categories/original/"
weight = 3

[main.params]
icon = "music"

[[main]]
identifier = "cover"
name = "カバー曲"
url = "/categories/cover/"
weight = 4

[main.params]
icon = "music"

[[main]]
identifier = "categories"
name = "Categories"
url = "/categories"
weight = 5

[main.params]
icon = "categories"

[[main]]
identifier = "tags"
name = "Tag"
url = "/tags"
weight = 6

[main.params]
icon = "tag"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/hyouhyan/himehina_lyricLab"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://x.com/hyouhyan"

[social.params]
icon = "brand-twitter"
