# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[main]]
identifier = "categories"
name = "Categories"
url = "/categories"
weight = 2

[main.params]
icon = "categories"

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/hyouhyan/himehina_lyricLab"

[social.params]
icon = "brand-github"

[[social]]
identifier = "twitter"
name = "Twitter"
url = "https://x.com/hyouhyan"

[social.params]
icon = "brand-twitter"
